cabal-version:      3.0
name:               misodoc2
version:            0.1.0.0
build-type:         Simple

executable app
  hs-source-dirs:
    src
  default-language:
    GHC2021
  default-extensions:
    TemplateHaskell

  if arch(wasm32)

    main-is:
      client.hs
    other-modules:
      Api
      Component
      FFI
      Markdown
      Model
    build-depends: 
      aeson,
      base,
      commonmark,
      commonmark-simple,
      jsaddle,
      miso,
      network-uri,
      pandoc-types,
      servant,
      servant-miso-router,
      text
    ghc-options:
      -Wall -O2 -no-hs-main -optl-mexec-model=reactor "-optl-Wl,--export=hs_start" -ddump-splices
    cpp-options:
      -DWASM

  else

    main-is:
      server.hs
    other-modules:
      Api
      Component
      FFI
      Markdown
      Model
    build-depends: 
      aeson,
      base,
      commonmark,
      commonmark-simple,
      http-types,
      jsaddle,
      miso,
      network-uri,
      optparse-applicative,
      pandoc-types,
      servant,
      servant-miso-html,
      servant-miso-router,
      servant-server,
      text,
      wai-extra,
      warp, wai,
      wai-app-static
    ghc-options:
      -Wall -O2 -ddump-splices

